
export const assistantSuggestions = [
    "I'm building a new 12x16 foot deck in my backyard.",
    "I'm planning a full kitchen remodel with semi-custom cabinets and quartz countertops.",
    "I need to repaint my living room and two bedrooms.",
    "I'm installing new laminate flooring in my basement.",
    "I need to pour a concrete slab for a new shed.",
    "I'm redoing my bathroom and need to buy new wallpaper.",
    "I'm trying to budget for a complete kitchen tear-out and remodel.",
    "How many boards do I need for a 20-foot long privacy fence?",
    "I'm painting a 15x20 ft room with 8 ft ceilings and want to know how many gallons I need.",
    "I need to calculate the amount of flooring for an L-shaped room.",
    "How many rolls of wallpaper are needed for a room with a 24-inch pattern repeat?",
    "Estimating the cost for a minor kitchen refresh with stock cabinets and laminate counters.",
    "I need to build a small 8x10 floating deck and need a materials list.",
    "How much concrete do I need for a 4-inch thick, 10x12 patio?",
    "I'm planning to tile my 100 sq ft bathroom floor.",
    "Budgeting for a high-end kitchen remodel with custom cabinets and a new appliance suite.",
    "I have to paint three rooms, each approximately 12x12 ft.",
    "Calculating the number of 5.5-inch wide deck boards for a 20x16 ft deck.",
    "I'm pouring footings for a new pergola and need to know how much concrete to mix.",
    "I'm getting quotes for a kitchen remodel and want a baseline estimate.",
    "How many 16ft deck boards are needed to cover 250 square feet?",
    "I need to paint the exterior of my house, which has about 2000 sq ft of wall surface.",
    "Planning to install vinyl plank flooring in three bedrooms totaling 500 sq ft.",
    "What's the cost difference between a basic and a premium kitchen renovation?",
    "I'm putting up a new fence and need to calculate how many posts I'll need.",
    "I'm replacing the furnace in my 2000 sq ft house in a cold climate.",
    "Planning to add new attic insulation to improve my home's efficiency.",
    "Thinking about upgrading my old AC unit to a new high-efficiency one.",
    "I want to install a mini-split system in my garage workshop.",
    "My energy bills are too high, I think my old AC is the problem.",
    "Need to figure out the right duct size for a new addition to my house.",
    "I want to compare the cost of a new furnace vs. a new heat pump.",
    "How much can I save by using a programmable thermostat?",
    "My home feels stuffy, I need to figure out the right HVAC load.",
    "Estimating the cost for a new 3-ton, 18 SEER heat pump.",
    "I'm considering blown-in cellulose for my attic and need to know how many bags to buy.",
    "What size air conditioner do I need for my 500 sq ft living room?",
    "Figuring out the cost to replace an old, inefficient oil furnace.",
    "I'm planning a new central air system and need to estimate ductwork sizes.",
    "I'm looking at a 2-zone mini-split system and need a cost estimate.",
    "How much could I save annually by upgrading from a 10 SEER to a 16 SEER AC?",
    "I need to add R-30 insulation to my 1200 sq ft attic.",
    "My furnace is old and I need to budget for a replacement.",
    "I'm building a sunroom and need to know what size mini-split to get.",
    "How do I calculate the correct HVAC system size for a 2,500 sq ft home in Zone 4?",
    "Comparing the running costs of a gas furnace versus an electric one.",
    "I want to see the payback period for a high-efficiency AC unit.",
    "Need to know the cost of a new 80,000 BTU gas furnace.",
    "I'm insulating my basement and need to know what R-value to aim for.",
    "What are the expected savings if I set my thermostat back 10 degrees at night?",
    "I need to fill three new 4x8 raised garden beds with soil.",
    "I'm fertilizing my 1500 sq ft lawn for the spring.",
    "I need to calculate how much mulch to buy for my flower beds.",
    "Planning my vegetable garden layout and need to figure out soil needs for different beds.",
    "How much topsoil do I need to level out my backyard?",
    "I bought a bag of 10-10-10 fertilizer and need to know how much to use on my vegetable garden.",
    "Starting a container garden on my patio and need to calculate soil volume for various pot sizes.",
    "I'm creating a new flower bed along a 30-foot fence line and need to know how much soil to order.",
    "How many cubic yards of soil do I need for a 10x10 garden that's 6 inches deep?",
    "I have a 5000 sq ft lawn and need to apply a starter fertilizer.",
    "I'm planning to top-dress my lawn with a quarter-inch of compost.",
    "Calculating how much potting mix I need for 10 large containers.",
    "I have a new lawn and need to figure out how much grass seed to buy.",
    "How much fertilizer do I need to apply 1 pound of nitrogen per 1000 sq ft?",
    "I'm building a new retaining wall and need to calculate the backfill.",
    "I need enough soil to fill two 3'x6'x1' raised beds.",
    "I want to apply a 2-inch layer of mulch to all my garden beds, which total about 200 sq ft.",
    "My soil test recommends adding 2 lbs of nitrogen to my garden.",
    "I'm overseeding my lawn and need to know how much seed to buy.",
    "How many bags of soil do I need if each bag is 1.5 cubic feet?",
    "I need to calculate the amount of gravel for a new garden path.",
    "I'm planning a new rose garden and need to amend the soil in a 10x20 ft area.",
    "My lawn is 2,500 sq ft. How much of a 5-10-5 fertilizer should I use?",
    "I'm filling a circular garden bed with a 10-foot diameter.",
    "I'm trying to figure out if it's cheaper to buy soil in bags or in bulk.",
    "I'm trying to figure out a budget for a new car purchase.",
    "I'm planning my retirement savings over the next 20 years.",
    "I'm looking to buy a new home and need to understand the mortgage costs.",
    "Comparing the energy usage of my old freezer to a new one.",
    "How much will my $5,000 investment be worth in 10 years at a 7% return?",
    "I need to figure out my monthly payment for a $400,000 mortgage.",
    "I want to see how much I can save on electricity by replacing all my light bulbs with LEDs.",
    "What are the total costs involved in a $25,000 car loan over 5 years?",
    "I'm saving for a down payment and want to see how long it will take.",
    "Calculating the monthly payment on a $500,000 home with a 30-year mortgage.",
    "I want to see the difference in annual cost between my old washing machine and a new one.",
    "I'm planning to invest $500 a month for 30 years and want to see the future value.",
    "I'm buying a car and need to account for a down payment and trade-in value.",
    "What's my PITI on a $350k mortgage with $5,000 in property taxes?",
    "How much energy savings can I expect by upgrading my 20-year-old refrigerator?",
    "I'm trying to reach a savings goal of $100,000.",
    "Calculating the loan payments for a new vehicle with a $40,000 price tag.",
    "How does a 15-year mortgage compare to a 30-year one for a $250,000 loan?",
    "I want to see how much interest I'll pay on a car loan.",
    "I'm upgrading from halogen lights to LED and want to estimate the savings.",
    "I want to start a college fund for my child and need to project its growth.",
    "What's the total cost of ownership for a car, including loan interest?",
    "How much faster can I pay off my mortgage by adding an extra $200 per month?",
    "Comparing two different investment scenarios with different interest rates.",
    "I need to see the energy cost of running my portable heater all winter.",
    "I'm planning a full home renovation, where do I start?",
    "What are the most cost-effective home improvement projects?",
    "How can I make my home more energy-efficient?",
    "I'm a first-time homebuyer, what are some common projects I should expect?",
    "What's the best project to increase my home's value?",
    "I want to build a deck and a fence, which calculators should I use?",
    "I'm remodeling my kitchen and bathroom, can you help me plan?",
    "What's the difference between a load-bearing and a non-load-bearing wall?",
    "How can I improve my home's curb appeal?",
    "What are some common DIY mistakes to avoid?",
    "How do I create a project budget?",
    "What's the best season for exterior painting?",
    "I need to re-caulk my windows, what's the best type of caulk to use?",
    "How do I find a reputable contractor?",
    "What are some essential tools every homeowner should have?",
    "I have a small budget, what's a good weekend project I can do?",
    "How do I know if I need a permit for my project?",
    "What are some safety tips for using power tools?",
    "How do I childproof my home?",
    "What are the best plants for a low-maintenance garden?",
    "I'm planning to sell my house, what projects have the best ROI?",
    "How do I build a simple raised garden bed?",
    "What's the difference between pre-qualifying and pre-approval for a mortgage?",
    "How can I tell if my windows need to be replaced?",
    "What are the pros and cons of an open-concept floor plan?",
    "How do I fix a leaky faucet?",
    "What's the best way to clean gutters?",
    "How do I patch a hole in drywall?",
    "What are some easy ways to update a bathroom without a full remodel?",
    "How do I choose the right interior paint color?",
    "What's the difference between a circuit breaker and a fuse box?",
    "How can I improve my home's lighting?",
    "What are some creative storage solutions for small spaces?",
    "How do I create a maintenance schedule for my home?",
    "What are the benefits of installing a ceiling fan?",
    "How do I test my smoke detectors and carbon monoxide detectors?",
    "What's the best way to organize a garage?",
    "How do I get rid of common household pests naturally?",
    "What are some tips for saving water at home?",
    "How do I build a simple fire pit in my backyard?",
    "What are the best flooring options for homes with pets?",
    "How do I choose the right size area rug for a room?",
    "What's the best way to wash windows for a streak-free shine?",
    "How do I properly ventilate my attic?",
    "What are the signs of a foundation problem?",
    "How do I create a cohesive color palette for my home?",
    "What are some popular interior design styles?",
    "How do I hang heavy pictures or mirrors securely?",
    "What's the best way to deep clean carpets?",
    "How do I maintain my garbage disposal?",
    "How do I perform a Manual J calculation for my home?",
    "What factors are most important for an accurate HVAC load calculation?",
    "Can you explain how climate zone affects HVAC load?",
    "What's the difference between heating load and cooling load?",
    "How does window area impact the overall HVAC load?",
    "Why is the number of occupants important for sizing an HVAC system?",
    "How does insulation quality (good, average, poor) change my HVAC needs?",
    "What happens if my HVAC system is oversized for my home's load?",
    "What are the risks of an undersized HVAC system?",
    "How do I find the total conditioned area of my house?",
    "Is it better to overestimate or underestimate my HVAC load?",
    "Can a load calculation help me save money on energy bills?",
    "How do I measure the total window area for the load calculator?",
    "What does 'conditioned area' mean?",
    "Why does the calculator ask for my U.S. Climate Zone?",
    "How does a high ceiling affect my HVAC load calculation?",
    "Does an unfinished basement contribute to the HVAC load?",
    "How often should I recalculate my home's HVAC load?",
    "Can I use the HVAC Load Calculator for a commercial building?",
    "What are some common mistakes when using an HVAC load calculator?",
    "How do I determine my home's insulation quality?",
    "Does the color of my roof affect my cooling load?",
    "How does a home's orientation (e.g., facing south) impact the HVAC load?",
    "What's a simplified way to understand HVAC load?",
    "Can planting trees around my house reduce my cooling load?",
    "How does air leakage (drafts) affect my HVAC load?",
    "What is a 'building envelope'?",
    "Does the type of foundation (slab, basement, crawlspace) matter for load calculation?",
    "How do heat-generating appliances factor into the cooling load?",
    "What's the ideal indoor temperature for summer and winter?",
    "How many BTUs do I need to cool a 500 sq ft room?",
    "What is a BTU and why is it important for air conditioners?",
    "How do I calculate the right AC size for my bedroom?",
    "Does a sunny room need a higher BTU air conditioner?",
    "How does poor insulation affect the required BTU for an AC unit?",
    "What ceiling height should I use in the BTU calculator?",
    "Is it better to get a window AC unit with more BTUs than I need?",
    "Can you convert BTUs to watts for me?",
    "How do I choose the right BTU for a portable air conditioner?",
    "Does the BTU calculator work for mini-split systems?",
    "What happens if my AC's BTU rating is too low for the room?",
    "Why does the calculator ask about sun exposure?",
    "How much does ceiling height influence the BTU calculation?",
    "What are the typical BTU ratings for different room sizes?",
    "Can I use this calculator for a central air conditioning system?",
    "If a room has an open doorway, how should I calculate the BTU?",
    "How does a kitchen's heat affect the AC size I need?",
    "How do I know if my room has 'good', 'average', or 'poor' insulation?",
    "Is there a difference in BTU needs for a top-floor room versus a ground-floor one?",
    "How many BTUs do I need for an oddly shaped room?",
    "What are the energy efficiency implications of choosing the wrong BTU size?",
    "Can I use a single large AC unit for multiple small rooms?",
    "How does the number of windows in a room affect the required BTUs?",
    "Explain how to use the AC Size (BTU) Calculator.",
    "What's a quick rule of thumb for estimating AC BTU needs?",
    "Do I need to account for people in the room for BTU calculation?",
    "How does a room's location (e.g., north-facing) impact BTU needs?",
    "What is the difference between a window AC and a portable AC?",
    "How much do high ceilings add to the required BTUs?",
    "Can a dehumidifier help my AC work more efficiently?",
    "How do I determine the right duct size for my HVAC system?",
    "What is CFM and how does it relate to duct size?",
    "What is 'friction loss' in an HVAC duct system?",
    "What happens if my HVAC ducts are too small?",
    "Can oversized ducts cause problems with my HVAC system?",
    "What's a common friction loss rate for a residential home?",
    "How do I calculate the CFM for a specific room?",
    "Is this duct size calculator for round or rectangular ducts?",
    "Why is the Duct Size Calculator intended for professional use?",
    "What is ACCA Manual D and how does it relate to duct sizing?",
    "How do I find the total CFM of my HVAC unit?",
    "What's the relationship between duct size and airflow velocity?",
    "Can I use this calculator for flex ducts?",
    "How does the length of a duct run affect the required size?",
    "What are the signs of poorly sized ductwork in a house?",
    "How do you convert a round duct size to an equivalent rectangular size?",
    "What materials are most common for residential ductwork?",
    "Does the type of duct material (metal vs. flex) affect the size calculation?",
    "How do bends and turns in ductwork impact friction loss?",
    "What is 'static pressure' and how does it influence duct design?",
    "Can I use this tool to size a kitchen vent hood duct?",
    "Why is proper duct sealing as important as proper duct sizing?",
    "What are some common mistakes in DIY duct installation?",
    "How can I improve airflow in my existing ductwork?",
    "Explain the inputs needed for the Duct Size Calculator.",
    "What is a 'ductulator'?",
    "How do I balance the airflow in my home's ductwork?",
    "What are dampers and how are they used in duct systems?",
    "Is it okay for ductwork to be in an unconditioned attic?",
    "How can I tell if my ducts are leaking?",
    "How much can I save by upgrading from a 10 SEER to a 16 SEER AC unit?",
    "What is a SEER rating?",
    "What's the difference between SEER and SEER2?",
    "How is the payback period calculated for a new AC unit?",
    "What is a good SEER2 rating for a new air conditioner in 2024?",
    "How does my local electricity rate affect my potential savings?",
    "What's the average number of cooling days per year in my region?",
    "How do I find the cooling capacity (BTU/hr) of my AC system?",
    "Does running my AC for more hours per day significantly impact savings?",
    "How can I find the total installed cost of a new AC unit for the calculator?",
    "Is a higher SEER rating always worth the extra cost?",
    "What does the cumulative savings chart show?",
    "Can this calculator be used for heat pumps as well?",
    "How accurate is the SEER Savings Calculator?",
    "What other factors besides SEER rating affect AC energy consumption?",
    "How do I find my cost per kWh on my electricity bill?",
    "What is a typical cooling capacity for a 2000 sq ft home?",
    "Can upgrading my insulation improve my savings even more?",
    "What's a simple way to understand how SEER works?",
    "Does the calculator account for different climate zones?",
    "How does maintenance affect an AC unit's SEER performance over time?",
    "What are the minimum SEER2 requirements in my area?",
    "Why is it important to match the indoor and outdoor units for best SEER performance?",
    "Does the calculator account for federal or local rebates?",
    "Explain all the inputs for the SEER Savings Calculator.",
    "What's the relationship between BTUs and tons for AC units?",
    "How does a variable-speed AC compare in terms of SEER?",
    "What is an EER rating?",
    "Can a smart thermostat increase the effective SEER of my system?",
    "How much energy can I save by cleaning my AC coils?",
    "How much does it cost to install a single-zone mini-split?",
    "What's the estimated cost for a 3-zone ductless mini-split system?",
    "How does the BTU rating of a mini-split affect its price?",
    "Is a higher SEER rating more expensive for a mini-split?",
    "What factors influence the total installation cost of a mini-split?",
    "What does 'zone' mean in the context of a mini-split system?",
    "How do I determine the total capacity needed for a multi-zone system?",
    "Is it cheaper to install one multi-zone unit or several single-zone units?",
    "What's a typical BTU rating for a bedroom mini-split?",
    "Does brand name significantly impact the cost of a mini-split?",
    "What are the labor costs associated with a mini-split installation?",
    "Can I install a mini-split myself to save money?",
    "How does the cost of a mini-split compare to a traditional central AC system?",
    "What is the average price per zone for a mini-split installation?",
    "Does the length of the line set affect the installation cost?",
    "Are there any hidden costs when installing a mini-split?",
    "Why does the estimator ask for a SEER2 rating?",
    "How does the type of indoor unit (wall-mounted, ceiling cassette) affect cost?",
    "What are the advantages of a ductless mini-split system?",
    "Can a mini-split provide heating as well as cooling?",
    "How do I choose the right size mini-split for my garage?",
    "What is the average lifespan of a mini-split system?",
    "Are there rebates or tax credits available for mini-splits?",
    "Explain the cost differences between different mini-split brands.",
    "Walk me through the inputs for the Mini-Split Cost Estimator.",
    "What kind of electrical work is needed for a mini-split?",
    "How do you hide the refrigerant lines for a cleaner look?",
    "What is a 'ceiling cassette' or 'floor-mounted' air handler?",
    "Can mini-splits be used for an entire house?",
    "How quiet are modern mini-split systems?",
    "What's the average cost to replace a gas furnace?",
    "How much does a new high-efficiency furnace cost?",
    "Is an electric furnace cheaper to install than a gas furnace?",
    "How does the size of my home affect the cost of a new furnace?",
    "What's the price difference between a standard and a high-efficiency furnace?",
    "How does my climate zone influence the furnace cost?",
    "What does AFUE mean for a furnace?",
    "What is a typical furnace size for a 2,500 sq ft home in a cold climate?",
    "Are oil furnaces more expensive than gas furnaces?",
    "Does the brand of the furnace greatly affect the price?",
    "What are the typical labor costs for a furnace installation?",
    "Can I save money by installing a furnace myself?",
    "How much more does a 95% AFUE furnace cost than an 80% AFUE one?",
    "What other costs are involved in a furnace replacement besides the unit itself?",
    "Why does the estimator need to know my home size and climate zone?",
    "What are the benefits of a high-efficiency furnace?",
    "How does the cost of a new furnace compare to a new heat pump?",
    "What are the signs that I need to replace my furnace?",
    "What is the average lifespan of a gas furnace?",
    "Does the complexity of the installation (e.g., in a tight attic) affect the cost?",
    "Are there any rebates available for high-efficiency furnaces?",
    "How do I choose between a single-stage and a two-stage furnace?",
    "What's a variable-speed furnace and is it worth the extra cost?",
    "Explain how to use the Furnace Cost Estimator.",
    "What's the typical cost range for a new furnace for a mid-sized home?",
    "Do I need to replace my ductwork when I replace my furnace?",
    "What is a 'condensing' furnace?",
    "How does a furnace's BTU output relate to my home size?",
    "What are the venting requirements for a high-efficiency furnace?",
    "How often should a furnace be serviced?",
    "How much does a new heat pump installation cost?",
    "What is the average cost of a 3-ton heat pump?",
    "How does the SEER2 rating affect the price of a heat pump?",
    "Is a higher efficiency heat pump worth the extra investment?",
    "What factors determine the total cost of a heat pump system?",
    "How does my home size influence the heat pump cost?",
    "What is the relationship between tonnage and heat pump price?",
    "Can you explain what a 'ton' of cooling means?",
    "What's a good SEER2 rating for a new heat pump?",
    "How do labor costs factor into the total heat pump installation price?",
    "Are there significant price differences between heat pump brands?",
    "Can I install a heat pump myself?",
    "How does the cost of a heat pump compare to a separate AC and furnace system?",
    "What are the main advantages of a heat pump?",
    "Are heat pumps effective in very cold climates?",
    "What are 'supplemental heating strips' for a heat pump?",
    "Does the calculator account for the cost of new ductwork?",
    "What's the typical lifespan of a heat pump?",
    "Are there government incentives for installing a high-efficiency heat pump?",
    "How do I determine the right size (tonnage) heat pump for my home?",
    "Explain how a heat pump works for both heating and cooling.",
    "What is HSPF rating for heat pumps?",
    "Does the cost estimator include the indoor air handler unit?",
    "What are some common signs that my old heat pump needs replacing?",
    "Walk me through the fields in the Heat Pump Cost Estimator.",
    "What is a 'dual fuel' system?",
    "How cold can it be before a heat pump is no longer effective?",
    "What is an 'inverter' heat pump?",
    "Do heat pumps require a lot of maintenance?",
    "How much quieter are new heat pumps compared to older models?",
    "How much can I save with a programmable thermostat?",
    "How many degrees should I set back my thermostat to save money?",
    "What's the ideal thermostat setting for when I'm away from home?",
    "Does setting the thermostat back for 8 hours a day make a big difference?",
    "How does my annual HVAC cost affect my potential savings?",
    "Is there a percentage of savings per degree of setback?",
    "How does a smart thermostat save more money than a programmable one?",
    "Can this calculator be used for both heating and cooling savings?",
    "What is a typical annual HVAC cost for a family home?",
    "Does the calculator work for Fahrenheit and Celsius?",
    "How do I find my annual HVAC cost?",
    "Is it better to have a consistent temperature all day or use setbacks?",
    "What's the optimal temperature for sleeping in the winter?",
    "Will constantly changing the thermostat damage my HVAC system?",
    "How long does it take for a home to heat up or cool down after a setback period?",
    "Can a zoning system with multiple thermostats increase my savings?",
    "What are the non-financial benefits of a smart thermostat?",
    "How does a thermostat 'learn' my schedule?",
    "Are there rebates available for purchasing a smart thermostat?",
    "How do I install a new thermostat?",
    "Explain the inputs for the Thermostat Savings Calculator.",
    "What's a reasonable setback temperature for summer?",
    "Does the location of my thermostat in the house matter?",
    "Can I control my smart thermostat with my phone?",
    "What other ways can I reduce my HVAC costs besides using a smart thermostat?",
    "Should I turn off my AC when I leave the house?",
    "What are some popular smart thermostat brands?",
    "How does a smart thermostat integrate with other smart home devices?",
    "What is a 'geofencing' feature on a smart thermostat?",
    "How can I tell if my old thermostat is inaccurate?",
    "How much attic insulation do I need for my climate zone?",
    "What is R-value for insulation?",
    "How do I measure my existing insulation depth?",
    "How many bags of blown-in cellulose do I need for a 1000 sq ft attic?",
    "What's the difference in coverage between fiberglass and cellulose insulation?",
    "How do I calculate the square footage of my attic?",
    "What is the recommended R-value for an attic in Zone 5?",
    "Can I add new insulation on top of my old insulation?",
    "How much deeper do I need to make my insulation to go from R-19 to R-49?",
    "Is cellulose insulation a better choice than fiberglass?",
    "What are the benefits of proper attic insulation?",
    "How do I find my U.S. Climate Zone for insulation purposes?",
    "What tools do I need to install blown-in attic insulation?",
    "Does the calculator account for the settling of loose-fill insulation?",
    "What's a typical R-value per inch for loose-fill fiberglass?",
    "Why is it important to air seal the attic before adding insulation?",
    "Can adding attic insulation lower my energy bills?",
    "How do I handle recessed lights and vents when adding insulation?",
    "What is the cost difference between fiberglass and cellulose insulation?",
    "What are the safety precautions for working in an attic with insulation?",
    "Does the calculator work for spray foam insulation?",
    "What's the difference between loose-fill and batt insulation?",
    "How do I know if I have enough attic insulation?",
    "What are attic rulers or markers?",
    "Explain how to use the Attic Insulation Calculator inputs.",
    "What is 'faced' vs. 'unfaced' insulation?",
    "Should the paper backing on insulation face up or down?",
    "What are attic ventilation baffles?",
    "How do I properly insulate my attic access door?",
    "Can I rent an insulation blower from a home improvement store?",
    "How do I calculate the right CFM for my bathroom fan?",
    "What does CFM mean for an exhaust fan?",
    "What's the recommended CFM for a 100 sq ft bathroom?",
    "How do I calculate the CFM needed for a kitchen exhaust fan?",
    "What are 'Air Changes per Hour' (ACH) and why do they matter?",
    "Why does a kitchen need a higher CFM fan than a bathroom?",
    "What's a good sone rating for a quiet bathroom fan?",
    "How do I calculate the volume of my room for the CFM calculation?",
    "What is the ASHRAE 62.2 standard for whole-house ventilation?",
    "How does the number of occupants affect whole-house ventilation needs?",
    "What's a suggested fan duct size for a 110 CFM fan?",
    "Can I use one fan for two bathrooms?",
    "What happens if my ventilation fan's CFM is too low?",
    "Is a higher CFM rating always better?",
    "What's the difference between an exhaust fan and a supply fan?",
    "How does my climate region affect whole-house ventilation strategies?",
    "What is an ERV or HRV system?",
    "Why is kitchen ventilation so important for indoor air quality?",
    "Does a bathroom with a shower need a higher CFM fan than one without?",
    "How do I convert CFM to metric units (liters per second)?",
    "What are the signs of poor ventilation in a home?",
    "Can I use this calculator for a workshop or garage fan?",
    "How does the length and complexity of the duct run affect fan performance?",
    "What is static pressure in relation to fans?",
    "Explain the different room type calculations in the Ventilation Fan CFM Calculator.",
    "Should my bathroom fan vent into the attic or outside?",
    "How do I install a bathroom ventilation fan?",
    "What is a 'duct booster fan'?",
    "Can I put my bathroom fan on a timer or humidity sensor?",
    "How do I clean my bathroom exhaust fan?",
    "What size dehumidifier do I need for a 1500 sq ft damp basement?",
    "What does 'pint capacity' mean for a dehumidifier?",
    "What's the difference between the new and old (pre-2019) dehumidifier sizing standards?",
    "How do I know if my room is 'moderately damp' or 'very damp'?",
    "What are the signs of 'wet' conditions in a room?",
    "What is the ideal humidity level for a basement?",
    "How does room area affect the recommended dehumidifier size?",
    "Why is a new 35-pint dehumidifier like an old 50-pint one?",
    "Can I use a smaller dehumidifier and just run it longer?",
    "What are the most important features to look for in a dehumidifier?",
    "What is a condensate pump and do I need one?",
    "How does a humidistat work on a dehumidifier?",
    "Why is an 'auto-defrost' feature important for a basement dehumidifier?",
    "What size dehumidifier is good for a small bathroom?",
    "Can a dehumidifier help with musty smells?",
    "How much energy does a typical dehumidifier use?",
    "What's the difference between a whole-house dehumidifier and a portable one?",
    "Where is the best place to position a dehumidifier in a room?",
    "How do I properly drain a dehumidifier with a hose?",
    "Can high humidity damage my home's structure?",
    "What's the relationship between temperature and relative humidity?",
    "Does the calculator recommend a specific brand?",
    "How often should I clean my dehumidifier's filter?",
    "What are the signs that my home has a humidity problem?",
    "Explain how to use the Dehumidifier Size Calculator.",
    "Can a dehumidifier make a room feel cooler?",
    "Does a dehumidifier use more electricity than an air conditioner?",
    "What are 'desiccant' dehumidifiers?",
    "How long does it take for a dehumidifier to lower the humidity in a room?",
    "Can I use a dehumidifier in a crawl space?",
    "How many gallons of paint do I need for a 12x15 foot room?",
    "How much area does one gallon of paint typically cover?",
    "How do I calculate the paintable area of a room?",
    "Does the calculator subtract area for windows and doors?",
    "Why do I need two coats of paint?",
    "How does the texture of a wall affect how much paint I need?",
    "Should I include the ceiling in my paint calculation?",
    "What's a standard size for a door and window when calculating paint?",
    "How do I calculate the perimeter of my room?",
    "Does the calculator work for both imperial (gallons) and metric (liters) units?",
    "What paint finish is best for a high-traffic hallway?",
    "How long should I wait between coats of paint?",
    "What are the essential tools for a painting project?",
    "How do I properly prepare a room for painting?",
    "Does dark paint require more coats than light paint?",
    "What is a primer and when do I need to use it?",
    "How can I calculate paint needed for an accent wall?",
    "How much extra paint should I buy for touch-ups?",
    "Does the calculator account for the specific brand of paint?",
    "How do I measure the height of my walls correctly?",
    "Can I use this calculator for exterior painting projects?",
    "What's the best way to clean my paint brushes and rollers?",
    "Explain the inputs for the Paint Coverage Calculator.",
    "How does the type of roller I use affect paint coverage?",
    "What is a 'wet edge' and why is it important when painting?",
    "How do I paint sharp, clean lines?",
    "What's the difference between latex and oil-based paint?",
    "Can I paint over glossy surfaces?",
    "How do I get rid of old paint cans?",
    "What are Low-VOC or Zero-VOC paints?",
    "How much flooring do I need for a 10x12 foot room?",
    "What is a 'waste factor' for flooring and why is it important?",
    "How do I calculate the square footage of an L-shaped room?",
    "How many boxes of laminate flooring do I need if each box covers 20 sq ft?",
    "What's a standard waste factor for a simple, rectangular room?",
    "When should I use a higher waste factor, like 15% or 20%?",
    "Does the calculator work for tile, laminate, and hardwood flooring?",
    "How do I measure my room's width and length accurately?",
    "Can I use this calculator for carpet installation?",
    "How do I convert square feet to square meters?",
    "What does the calculator mean by 'box coverage'?",
    "How do I find the box coverage on the flooring packaging?",
    "Should I buy extra flooring for future repairs?",
    "What's the best way to handle transitions between different types of flooring?",
    "How do I prepare a subfloor for new flooring installation?",
    "What are the pros and cons of different flooring materials?",
    "Does the direction I lay my flooring planks matter?",
    "What is an underlayment and do I always need it?",
    "How do I cut flooring planks accurately?",
    "What tools are essential for a DIY flooring project?",
    "Can I install new flooring on top of old flooring?",
    "How do I account for closets and alcoves in my calculation?",
    "Explain how to use the Flooring Calculator.",
    "What's a common mistake people make when buying flooring?",
    "How much of an expansion gap should I leave for laminate flooring?",
    "What is luxury vinyl plank (LVP) flooring?",
    "How do I install quarter-round or baseboard molding after installing the floor?",
    "What is the Janka hardness scale for wood floors?",
    "How do I repair a scratch in a hardwood floor?",
    "Is engineered hardwood the same as laminate?",
    "How many rolls of wallpaper do I need for my bedroom?",
    "How do I calculate the number of wallpaper strips needed?",
    "What is 'pattern repeat' and how does it affect how much wallpaper I need?",
    "Why is the waste factor so high for wallpaper (15%)?",
    "How do I measure the perimeter of my room for wallpapering?",
    "What are the standard dimensions of a wallpaper roll?",
    "How many strips can I typically get from a single roll of wallpaper?",
    "Do I need more wallpaper for a large pattern repeat?",
    "What's the difference between a 'single roll' and a 'double roll'?",
    "How do I prepare my walls before applying wallpaper?",
    "What is wallpaper 'booking' and why is it important?",
    "Can I apply new wallpaper over old wallpaper?",
    "What tools do I need for hanging wallpaper?",
    "How do I match the pattern correctly between strips?",
    "What's the best way to handle corners when wallpapering?",
    "How do I cut around windows and outlets?",
    "Should I start wallpapering in a corner or in the middle of a wall?",
    "What is a 'plumb line' and why is it critical for wallpapering?",
    "How do I avoid bubbles and wrinkles in my wallpaper?",
    "Can I use this calculator for peel-and-stick wallpaper?",
    "How do I calculate wallpaper needed for just an accent wall?",
    "What's the best way to clean wallpaper?",
    "How difficult is it to remove old wallpaper?",
    "Explain all the fields in the Wallpaper Calculator.",
    "What is a 'pattern match' (e.g., straight, drop)?",
    "Can I wallpaper a bathroom?",
    "What is sizing and should I apply it before wallpapering?",
    "How do I fix a tear in my wallpaper?",
    "Is wallpaper making a comeback?",
    "What are some popular wallpaper trends?",
    "What's a realistic budget for a kitchen remodel?",
    "How much does the average kitchen renovation cost?",
    "What's the cost difference between stock, semi-custom, and custom cabinets?",
    "Are granite countertops much more expensive than laminate?",
    "How does the quality of appliances affect the total remodel cost?",
    "What's the biggest cost component in a typical kitchen remodel?",
    "How does the size of my kitchen impact the overall cost?",
    "Is this estimator for a full gut-and-remodel or just a cosmetic update?",
    "What does 'appliance tier' mean?",
    "What are some ways to save money on a kitchen remodel?",
    "What's the difference between solid-surface and quartz countertops?",
    "Does the calculator include labor costs?",
    "How accurate is the Kitchen Remodel Estimator?",
    "What are some common 'hidden costs' in a kitchen renovation?",
    "Should I budget for a contingency fund?",
    "How much value does a kitchen remodel add to a home?",
    "What are the first steps in planning a kitchen remodel?",
    "How do I measure the size of my kitchen in square feet?",
    "Does the estimator account for plumbing or electrical work?",
    "What's the difference between a 'basic', 'mid-range', and 'high-end' appliance package?",
    "How can I create a functional kitchen layout?",
    "What are some popular kitchen design trends right now?",
    "How long does a typical kitchen remodel take?",
    "What are some durable and low-maintenance materials for a kitchen?",
    "Explain how to use the Kitchen Remodel Estimator.",
    "What is the 'kitchen work triangle'?",
    "Should I replace my cabinets or reface them?",
    "What are the pros and cons of an undermount sink?",
    "How much should I spend on appliances relative to the total budget?",
    "Is an open-concept kitchen a good idea?",
    "How many deck boards do I need for a 12x16 foot deck?",
    "How do I calculate the number of joists for my deck frame?",
    "What is standard joist spacing for a deck?",
    "How do I account for the gap between deck boards in my calculation?",
    "What's a typical waste factor for decking materials?",
    "What are the standard lengths of deck boards?",
    "How do I choose between 12-foot and 16-foot deck boards?",
    "Does the calculator estimate screws and hardware?",
    "What is the actual width of a '5/4x6' deck board?",
    "How does the decking calculator work for metric units?",
    "Can I use this calculator for composite decking as well as wood?",
    "What does 'on-center' spacing mean for joists?",
    "How do I determine the 'length' vs 'width' of my deck for the calculator?",
    "What materials do I need for the deck's foundation (footings)?",
    "How do I build a deck that is safe and up to code?",
    "What kind of wood is best for deck framing?",
    "Should I use hidden fasteners or deck screws?",
    "How deep should my deck footings be?",
    "What's a ledger board and how do I attach it to my house?",
    "How can I ensure my deck layout is square?",
    "What are some common mistakes when building a deck?",
    "Explain the inputs for the Decking Materials Calculator.",
    "Does the calculator help with stair construction?",
    "How do I estimate the amount of concrete needed for my deck posts?",
    "What is the difference between pressure-treated wood and cedar for a deck?",
    "How often do I need to stain or seal a wood deck?",
    "Can I build a deck over an existing concrete patio?",
    "What are joist hangers and why are they important?",
    "What's the best way to clean a deck before staining?",
    "Is a floating deck easier to build than an attached deck?",
    "How much concrete do I need for a 10x10 foot patio?",
    "How do I calculate the volume of a concrete slab in cubic yards?",
    "How many 80lb bags of concrete do I need for my project?",
    "What is a standard thickness for a residential concrete slab?",
    "Why do I need a waste factor for concrete?",
    "What's the difference between cubic feet and cubic yards?",
    "How do I convert cubic meters to cubic yards?",
    "What is the typical yield of an 80lb bag of concrete mix?",
    "Can I use this calculator for round concrete footings?",
    "How do I prepare the ground for a concrete slab?",
    "What is a 'gravel base' and why is it important?",
    "What is rebar or wire mesh used for in a concrete slab?",
    "How long does it take for concrete to cure?",
    "What are 'control joints' and why are they necessary?",
    "What tools do I need for a small concrete project?",
    "Is it cheaper to buy bagged concrete or have it delivered?",
    "What's the ideal weather for pouring concrete?",
    "How do I get a smooth finish on my concrete slab?",
    "Can I pour concrete directly on soil?",
    "How do I prevent my concrete from cracking?",
    "What's the difference between concrete and cement?",
    "Explain the fields in the Concrete Slab Calculator.",
    "How much water do I add to a bag of concrete mix?",
    "What strength (PSI) of concrete do I need for a driveway?",
    "Can I add color to my concrete?",
    "How do I fix a small crack in my existing concrete?",
    "What is an 'expansion joint'?",
    "How do I build the forms for a concrete slab?",
    "What is 'screeding' concrete?",
    "How long should I wait before walking on a new concrete slab?",
    "How many bundles of shingles do I need for a 1,500 sq ft roof?",
    "What is a 'roofing square'?",
    "How does roof pitch affect the amount of material I need?",
    "What is a typical waste factor for a roofing project?",
    "How do I calculate the actual surface area of my roof?",
    "What is a 6/12 roof pitch?",
    "How do I measure my roof's ground-level area?",
    "Does the calculator work for metal roofing or just asphalt shingles?",
    "How many bundles of shingles are in one square?",
    "What does the pitch multiplier do?",
    "Can I use this for a hip roof or just a simple gable roof?",
    "How do I determine my roof's pitch?",
    "What other materials do I need besides shingles?",
    "What is roofing underlayment and is it required?",
    "What is 'flashing' and where is it used on a roof?",
    "What are the most common types of roofing materials?",
    "How much more material does a steep roof require compared to a low-slope roof?",
    "Can I install a new roof over my old one?",
    "What are the safety precautions for working on a roof?",
    "How do I estimate the cost of a new roof?",
    "What is the lifespan of asphalt shingles?",
    "How do I find a reputable roofing contractor?",
    "What's the difference between 3-tab shingles and architectural shingles?",
    "Explain how to use the Roofing Materials Calculator.",
    "What are the signs that my roof needs to be replaced?",
    "What is a 'drip edge'?",
    "How do I handle ventilation in my roof and attic?",
    "What's the best time of year to replace a roof?",
    "How do I properly nail roofing shingles?",
    "What kind of warranty comes with a new roof?",
    "How many 12x24 inch tiles do I need for a 100 sq ft bathroom floor?",
    "How much extra tile should I buy for a herringbone pattern?",
    "What is a good waste factor for a tile project?",
    "How does grout line width affect the number of tiles I need?",
    "How do I calculate the total area of material required, including waste?",
    "Can I use this calculator for both floor and wall tile?",
    "How do I find the area of my room in square feet?",
    "What's the difference between porcelain and ceramic tile?",
    "What size trowel should I use for large format tiles?",
    "How do I plan my tile layout to avoid small cuts?",
    "Do I need to seal natural stone tiles?",
    "What is thin-set mortar?",
    "How long should I wait before grouting my new tile?",
    "What's the best way to cut tile?",
    "Can I tile over an existing tile floor?",
    "How do I prepare my subfloor for tiling?",
    "What are some common tiling mistakes to avoid?",
    "How do I calculate the amount of grout I need?",
    "How do I estimate the cost of my tile project?",
    "What is 'lippage' and how can I prevent it?",
    "Explain how to use the Tile Calculator.",
    "What is a wet saw and do I need to rent one?",
    "How do I remove old grout?",
    "What are tile spacers?",
    "Is it better to start tiling from the center of the room or a wall?",
    "What is a 'Schluter edge'?",
    "How do I tile a shower wall?",
    "What is the PEI rating for tile?",
    "Can I use floor tile on a wall?",
    "How do I clean grout?",
    "How many sheets of drywall do I need for a room?",
    "Does the drywall calculator estimate screws and mud?",
    "What size drywall sheets should I use, 4x8 or 4x12?",
    "How do I calculate the total wall and ceiling area?",
    "What is 'green board' drywall used for?",
    "What is Type X fire-resistant drywall?",
    "How much joint compound do I need for a room?",
    "What's a good estimate for the number of drywall screws needed?",
    "How do I account for waste when ordering drywall?",
    "Should I hang drywall vertically or horizontally?",
    "How do I finish drywall to get a smooth surface?",
    "What are the steps for taping and mudding drywall joints?",
    "What tools do I need for a drywall project?",
    "How do I cut drywall sheets?",
    "Can I hang drywall by myself?",
    "What is a corner bead and where is it used?",
    "How many coats of joint compound are typically needed?",
    "What's the best way to sand drywall without making a huge mess?",
    "Do I need to prime new drywall before painting?",
    "How do I repair a hole in my drywall?",
    "Explain the inputs for the Drywall Calculator.",
    "What's the difference in weight between regular and lightweight drywall?",
    "How far apart should drywall screws be placed?",
    "How do I cut holes for outlets and switches in drywall?",
    "What is a 'butt joint' vs. a 'tapered joint'?",
    "How do I handle drywalling a ceiling?",
    "What is 'skim coating'?",
    "Can I use mesh tape instead of paper tape for drywall?",
    "How do I match an existing wall texture?",
    "What's the best way to dispose of drywall scraps?",
    "How many fence posts do I need for a 150-foot fence line?",
    "How far apart should I space my fence posts?",
    "How do I calculate the number of pickets for a privacy fence?",
    "How many horizontal rails are needed for a 6-foot tall fence?",
    "What's the difference between using pre-made panels and building with individual pickets?",
    "How do I account for gates in my fence material calculation?",
    "What are the most common materials for fencing?",
    "How deep should I set my fence posts in the ground?",
    "Do I need to put concrete in every fence post hole?",
    "How do I find my property line before building a fence?",
    "What are the typical dimensions of a fence panel?",
    "What's a good spacing for pickets on a shadowbox fence?",
    "How do I estimate the cost of my fence project?",
    "What's the best type of wood for a long-lasting fence?",
    "How do I prevent my fence posts from rotting?",
    "What tools are required for building a wood fence?",
    "How do I ensure my fence is straight?",
    "What are local regulations I should check before building a fence?",
    "How do I build a gate for my new fence?",
    "What's the difference between wood and vinyl fencing?",
    "Explain the fields in the Fence Materials Calculator.",
    "How do I handle a slope or hill when building a fence?",
    "What kind of hardware do I need for a fence gate?",
    "How often do I need to stain or seal a wood fence?",
    "What is a 'string line' and how is it used for fencing?",
    "How do I attach fence rails to the posts?",
    "What's the difference between a privacy fence and a picket fence?",
    "Can I build a fence in the winter?",
    "How do I deal with tree roots when digging post holes?",
    "What are the pros and cons of a chain-link fence?",
    "How much gravel do I need for a driveway base?",
    "How do I calculate the amount of concrete for a driveway?",
    "How many tons of asphalt are needed for a 10x50 foot driveway?",
    "What is the recommended depth for a gravel sub-base?",
    "How thick should a residential concrete driveway be?",
    "What are the pros and cons of concrete vs. asphalt driveways?",
    "How many 4x8 pavers do I need for a 400 sq ft patio?",
    "How do I estimate the material cost for a new driveway?",
    "What kind of gravel is best for a driveway base?",
    "Why is a compacted base so critical for a driveway's longevity?",
    "Can I use this calculator for a walkway or just a driveway?",
    "How does the calculator estimate the number of pavers?",
    "What does the estimator use for the weight of asphalt?",
    "How do I prepare the site for a new driveway?",
    "Is a paver driveway more expensive than a concrete one?",
    "How long does an asphalt driveway need to cure before I can park on it?",
    "What maintenance is required for an asphalt driveway?",
    "How do I prevent a concrete driveway from cracking?",
    "Explain the inputs for the Driveway Materials Calculator.",
    "Can I install a paver driveway myself?",
    "What is the 'crown' of a driveway and why is it important?",
    "How do I properly compact a gravel base?",
    "What's the difference between hot-mix asphalt and cold patch?",
    "How often should I seal my asphalt driveway?",
    "What are the different finish options for a concrete driveway (brushed, stamped)?",
    "How do I deal with drainage for my driveway?",
    "What is 'polymeric sand' for paver joints?",
    "Can I put a new layer of asphalt over an old one?",
    "How cold is too cold to pour concrete?",
    "What are the benefits of a permeable paver driveway?",
    "How many cubic yards of mulch do I need to cover my flower beds?",
    "How do I calculate the volume of soil for a raised garden bed?",
    "How many 2 cu ft bags of topsoil do I need for a 4x8 garden bed that's 6 inches deep?",
    "What is the recommended depth for mulch?",
    "What's the recommended depth for a new vegetable garden?",
    "How do I convert cubic feet to cubic yards?",
    "How many liters are in a cubic foot?",
    "Is it cheaper to buy soil in bags or in bulk?",
    "What is the difference between topsoil, garden soil, and potting mix?",
    "Can I use this calculator for gravel or decorative stone?",
    "How do I measure the dimensions of an irregularly shaped garden bed?",
    "What are the benefits of adding mulch to my garden?",
    "What kind of mulch is best for vegetable gardens?",
    "How do I calculate the soil needed for a circular garden bed?",
    "What are 'soil amendments' and why are they listed as an option?",
    "How often should I replace or top up mulch?",
    "What's the difference between compost and topsoil?",
    "Explain how to use the Soil & Mulch Calculator.",
    "How do I prepare an area for a new layer of topsoil?",
    "Can I put mulch directly on top of weeds?",
    "What is landscape fabric and should I use it under my mulch?",
    "How do I calculate the volume of soil needed for pots and containers?",
    "What's a good all-purpose depth for a flower bed?",
    "Does the calculator account for soil compaction?",
    "What is 'sheet mulching' or lasagna gardening?",
    "What are the pros and cons of different mulch types (wood, straw, plastic)?",
    "How can I make my own compost?",
    "What is soil pH and why does it matter?",
    "How do I improve clay soil?",
    "What is 'loam'?",
    "How much 10-10-10 fertilizer do I need for a 5000 sq ft lawn?",
    "What do the numbers on a fertilizer bag mean (N-P-K)?",
    "What's a typical application rate of nitrogen for a lawn?",
    "How do I get a soil test for my garden?",
    "How does the fertilizer ratio affect the amount I need to apply?",
    "Can I use this calculator for both granular and liquid fertilizer?",
    "What is 'pounds of Nitrogen per 1000 sq ft'?",
    "How do I convert the metric application rate to imperial?",
    "Is it bad to over-fertilize my lawn or garden?",
    "When is the best time of year to fertilize my lawn?",
    "What's the difference between synthetic and organic fertilizers?",
    "What are the signs of a nitrogen deficiency in plants?",
    "How do I properly spread granular fertilizer?",
    "Can I fertilize my garden and lawn with the same product?",
    "What is a 'starter fertilizer'?",
    "How does phosphorus (P) help my plants?",
    "What is the role of potassium (K) in plant health?",
    "Explain the inputs for the Fertilizer Needs Calculator.",
    "Should I water my lawn after applying fertilizer?",
    "How long does slow-release fertilizer last?",
    "What are some natural sources of nitrogen for my garden?",
    "Is it necessary to fertilize my vegetable garden?",
    "How do I calculate the square footage of my lawn?",
    "What safety precautions should I take when handling fertilizer?",
    "What does 'soil amendment' mean?",
    "Can I use coffee grounds as fertilizer?",
    "What is 'compost tea'?",
    "Is it better to fertilize before or after it rains?",
    "What is 'fertilizer burn'?",
    "How do I choose the right fertilizer spreader?",
    "Is a tankless water heater cheaper to operate than a tank model?",
    "How much can I save annually by switching to a tankless water heater?",
    "What's the payback period for upgrading to a tankless water heater?",
    "How do I find my local energy rate ($/kWh)?",
    "What is a typical groundwater temperature?",
    "Why does the temperature of incoming water affect my energy costs?",
    "How much hot water does an average family of four use per day?",
    "What is 'standby heat loss' in a tank water heater?",
    "Does this calculator work for gas water heaters?",
    "What is a heat pump water heater and is it efficient?",
    "How does the set temperature of my water heater impact my bill?",
    "What is a safe and efficient temperature to set my water heater to?",
    "How much does a new tankless water heater cost to install?",
    "What are the pros and cons of tank vs. tankless water heaters?",
    "Explain the inputs for the Water Heater Energy Cost Calculator.",
    "How does a higher 'First Hour Rating' benefit me?",
    "Can I install a tankless water heater myself?",
    "What maintenance does a tankless water heater require?",
    "What are the signs that my current water heater is failing?",
    "How long does a typical tank water heater last?",
    "Does the calculator account for differences in UEF rating?",
    "What is the Uniform Energy Factor (UEF)?",
    "How can I reduce my overall hot water usage?",
    "What's the cost difference between an electric and gas tankless heater?",
    "How do I flush my tank water heater?",
    "What is an anode rod and when should it be replaced?",
    "Can I put my water heater on a timer to save money?",
    "Is a point-of-use tankless heater a good idea for a single sink?",
    "What are the venting requirements for a gas tankless water heater?",
    "How do I know what size water heater I need for my family?",
    "How much can I save on my electric bill with solar panels?",
    "What's the return on investment (ROI) for a home solar system?",
    "How do I calculate the payback period for solar panels?",
    "What is a 'peak sunlight hour' and how do I find it for my location?",
    "How do I estimate the size (kW) of the solar system I need?",
    "What is the federal solar tax credit (ITC)?",
    "Are there state or local rebates for solar installations?",
    "How does my average monthly bill help determine the system size I need?",
    "What is the average cost of a residential solar panel installation?",
    "How many solar panels would I need for a 2000 sq ft house?",
    "How does the calculator estimate the environmental impact (CO2, trees)?",
    "What is 'net metering'?",
    "Does the calculator account for the degradation of solar panels over time?",
    "What is a reasonable 'system efficiency factor' to assume?",
    "Explain the inputs for the Solar Savings Calculator.",
    "How does the orientation (south, east, west) of my roof affect solar production?",
    "Can I install solar panels on a flat roof?",
    "What maintenance do solar panels require?",
    "What is the typical lifespan of a solar panel system?",
    "How does having a home battery (like a Powerwall) affect my savings?",
    "What are the pros and cons of leasing vs. buying solar panels?",
    "How do solar panels increase my home's value?",
    "What happens when the power goes out if I have solar panels?",
    "Can solar panels power my whole house?",
    "What is a 'solar inverter' and what does it do?",
    "What's the difference between monocrystalline and polycrystalline panels?",
    "How do I find a qualified solar installer?",
    "Do solar panels work on cloudy days?",
    "Do I need to clean my solar panels?",
    "What is a 'grid-tied' solar system?",
    "How do I fix a leaky faucet in my kitchen?",
    "What's the first step to patching a small hole in my drywall?",
    "How do I unclog a drain without using harsh chemicals?",
    "Can you give me a simple recipe for a non-toxic all-purpose cleaner?",
    "What's the best way to remove a stripped screw?",
    "How do I silence a squeaky door hinge?",
    "What's an easy way to improve my home's curb appeal on a budget?",
    "How do I clean my garbage disposal?",
    "What's the proper way to test a smoke detector?",
    "How can I get rid of fruit flies in my kitchen?",
    "What's a good temperature to set my water heater to for savings and safety?",
    "How do I reset a tripped circuit breaker?",
    "What's the best way to clean stainless steel appliances?",
    "How do I fix a running toilet?",
    "What's a simple method for organizing my pantry?",
    "How do I sharpen my kitchen knives?",
    "What's the best way to remove hard water stains from a shower head?",
    "How can I make my small room feel bigger?",
    "What's an easy-to-grow herb for a beginner gardener?",
    "How do I clean my coffee maker?",
    "What's the best way to remove pet hair from furniture?",
    "How can I naturally deter mosquitoes from my patio?",
    "What's a simple way to update my kitchen cabinets without replacing them?",
    "How do I get rid of weeds in my lawn without chemicals?",
    "What's the best way to store leftover paint?",
    "How do I fix a wobbly chair or table?",
    "What's an easy way to create a family command center?",
    "How do I clean my dishwasher to remove odors?",
    "What's a good schedule for washing my bed pillows?",
    "How do I properly dispose of old electronics?",
    "What are some key things to consider before buying a new mattress?",
    "How can I make my home smell fresh and clean naturally?",
    "What's the best way to organize my closet?",
    "How do I create a cozy reading nook?",
    "What are some tips for a successful garage sale?",
    "How do I choose the right light bulbs for each room?",
    "What's an easy way to make my own compost?",
    "How do I keep my houseplants alive?",
    "What's a simple way to create a gallery wall?",
    "How do I clean my oven without harsh chemicals?",
    "What are some must-have items for a home emergency kit?",
    "How do I properly set up a home office for productivity?",
    "What's the best way to clean my makeup brushes?",
    "How do I create a relaxing bedtime routine?",
    "What's a good way to organize my digital files and photos?",
    "How do I care for my cast iron skillet?",
    "What are some easy ways to reduce food waste?",
    "How do I choose the right pillow for my sleeping style?",
    "What's a simple workout routine I can do at home?",
    "How do I create a budget and stick to it?",
    "What are some healthy and easy meal prep ideas?",
    "How can I improve my home's air quality?",
    "What's the best way to clean my windows and mirrors for a streak-free shine?",
    "How do I get rid of musty smells in my basement?",
    "What are some tips for saving money on groceries?",
    "How do I properly care for my leather shoes and bags?",
    "What's a simple way to create a beautiful tablescape for a dinner party?",
    "How do I organize my fridge and freezer for maximum efficiency?",
    "What are some fun and educational activities to do with kids at home?",
    "How do I create a pet-friendly home?",
    "What's the best way to clean my grill?",
    "How do I get rid of ants in my kitchen naturally?",
    "What are some tips for growing tomatoes in a pot?",
    "How do I make a perfect cup of coffee at home?",
    "What's the best way to store seasonal clothing?",
    "How do I create a welcoming entryway?",
    "What are some easy ways to add color to a neutral room?",
    "How do I get rid of junk mail?",
    "What's the best way to clean my keyboard and computer screen?",
    "How do I create a relaxing at-home spa day?",
    "What are some tips for a more sustainable lifestyle?",
    "How do I choose the right type of fire extinguisher for my home?",
    "What's a simple way to make my own candles?",
    "How do I care for my wooden cutting boards?",
    "What are some fun and free things to do in my city?",
    "How do I start a conversation with a new neighbor?",
    "What's a good way to organize my recipes?",
    "How do I keep my flowers fresh for longer?",
    "What are some tips for a better night's sleep?",
    "How do I create a beautiful and functional laundry room?",
    "What's the best way to remove red wine stains?",
    "How do I create a family-friendly living room?",
    "What are some tips for successful container gardening?",
    "How do I properly store my holiday decorations?",
    "What's a good way to organize my jewelry?",
    "How do I create a backyard oasis on a budget?",
    "What are some tips for traveling with kids?",
    "How do I make a great smoothie?",
    "What's the best way to clean my area rugs?",
    "How do I create a homework station for my kids?",
    "What are some tips for hosting a stress-free party?",
    "How do I choose the right houseplants for my home's lighting conditions?",
    "What's a good way to organize my craft supplies?",
    "How do I create a beautiful and edible garden?",
    "What are some tips for a successful road trip?",
    "How do I make a delicious and healthy salad?",
    "What's the best way to clean my microwave?",
    "How do I create a fun and functional playroom for my kids?",
    "What are some tips for staying productive when working from home?",
    "How do I choose the right dog bed for my furry friend?",
    "What's a good way to organize my spice rack?",
    "How do I create a beautiful and low-maintenance front yard?",
    "What are some tips for a successful camping trip?",
    "How do I make a delicious and healthy breakfast?",
    "What's the best way to clean my refrigerator coils?",
    "How do I create a comfortable and stylish home theater?",
    "What are some tips for staying organized with a busy schedule?",
    "How do I choose the right hamster cage for my furry friend?",
    "What's a good way to organize my pantry and cabinets?",
    "How do I create a beautiful and fragrant garden?",
    "What are some tips for a successful backyard barbecue?",
    "How do I make a delicious and healthy snack?",
    "What's the best way to clean my window blinds and shades?",
    "How do I create a relaxing and rejuvenating bathroom retreat?",
    "What are some tips for staying positive and motivated?",
    "How do I choose the right reptile enclosure for my scaly friend?",
    "What's a good way to organize my garage and shed?",
    "How do I create a beautiful and edible landscape?",
    "What are some tips for a successful pool party?",
    "How do I make a delicious and healthy dessert?",
    "What's the best way to clean my baseboards and trim?",
    "How do I create a stylish and functional home bar?",
    "What are some tips for setting and achieving goals?",
    "How do I choose the right bird cage for my feathered friend?",
    "What's a good way to organize my closet and drawers?",
    "How do I create a beautiful and low-maintenance garden?",
    "What are some tips for a successful game night?",
    "How do I make a delicious and healthy smoothie?",
    "What's the best way to clean my walls and ceilings?",
    "How do I create a cozy and inviting fireplace area?",
    "What are some tips for practicing mindfulness and meditation?",
    "How do I choose the right small animal cage for my furry friend?",
    "What's a good way to organize my laundry room and supplies?",
    "How do I create a beautiful and wildlife-friendly garden?",
    "What are some tips for a successful holiday gathering?",
    "How do I make a delicious and healthy soup?",
    "What's the best way to clean my carpets and rugs?",
    "How do I create a comfortable and stylish outdoor living space?",
    "What are some tips for building healthy habits?",
    "How do I choose the right ferret cage for my furry friend?",
    "What's a good way to organize my home office and paperwork?",
    "How do I create a beautiful and vertical garden?",
    "What are some tips for a successful dinner party?",
    "How do I make a delicious and healthy pizza?",
    "What's the best way to clean my hardwood floors?",
    "How do I create a functional and stylish entryway?",
    "What are some tips for improving my communication skills?",
    "How do I choose the right rabbit hutch for my furry friend?",
    "What's a good way to organize my bathroom and toiletries?",
    "How do I create a beautiful and hydroponic garden?",
    "What are some tips for a successful brunch?",
    "How do I make a delicious and healthy pasta dish?",
    "What's the best way to clean my tile and grout?",
    "How do I create a cozy and inviting living room?",
    "What are some tips for managing stress and anxiety?",
    "How do I choose the right chinchilla cage for my furry friend?",
    "What's a good way to organize my craft room and supplies?",
    "How do I create a beautiful and succulent garden?",
    "What are some tips for a successful potluck?",
    "How do I make a delicious and healthy stir-fry?",
    "What's the best way to clean my laminate floors?",
    "How do I create a functional and stylish dining room?",
    "What are some tips for improving my time management skills?",
    "How do I choose the right rat cage for my furry friend?",
    "What's a good way to organize my game room and entertainment center?",
    "How do I create a beautiful and rock garden?",
    "What are some tips for a successful tea party?",
    "How do I make a delicious and healthy taco?",
    "What's the best way to clean my vinyl floors?",
    "How do I create a cozy and inviting sunroom?",
    "What are some tips for improving my problem-solving skills?",
    "How do I choose the right mouse cage for my furry friend?",
    "What's a good way to organize my music room and instruments?",
    "How do I create a beautiful and water garden?",
    "What are some tips for a successful wine tasting party?",
    "How do I make a delicious and healthy burger?",
    "What's the best way to clean my natural stone floors?",
    "How do I create a functional and stylish library?",
    "What are some tips for improving my creativity?",
    "How do I choose the right degu cage for my furry friend?",
    "What's a good way to organize my home gym and equipment?",
    "How do I create a beautiful and shade garden?",
    "What are some tips for a successful cheese tasting party?",
    "How do I make a delicious and healthy burrito?",
    "What's the best way to clean my cork floors?",
    "How do I create a cozy and inviting screened porch?",
    "What are some tips for improving my leadership skills?",
    "How do I choose the right gerbil cage for my furry friend?",
    "What's a good way to organize my sewing room and supplies?",
    "How do I create a beautiful and butterfly garden?",
    "What are some tips for a successful chocolate tasting party?",
    "How do I make a delicious and healthy quesadilla?",
    "What's the best way to clean my bamboo floors?",
    "How do I create a functional and stylish playroom?",
    "What are some tips for improving my public speaking skills?",
    "How do I choose the right hedgehog cage for my furry friend?",
    "What's a good way to organize my workshop and tools?",
    "How do I create a beautiful and hummingbird garden?",
    "What are some tips for a successful coffee tasting party?",
    "How do I make a delicious and healthy wrap?",
    "What's the best way to clean my concrete floors?",
    "How do I create a cozy and inviting patio?",
    "What are some tips for improving my networking skills?",
    "How do I choose the right sugar glider cage for my furry friend?",
    "What's a good way to organize my art studio and supplies?",
    "How do I create a beautiful and rain garden?",
    "What are some tips for a successful beer tasting party?",
    "How do I make a delicious and healthy omelet?",
    "What's the best way to clean my rubber floors?",
    "How do I create a functional and stylish home office?",
    "What are some tips for improving my negotiation skills?",
    "How do I choose the right hamster habitat for my furry friend?",
    "What's a good way to organize my photography studio and equipment?",
    "How do I create a beautiful and bog garden?",
    "What are some tips for a successful whiskey tasting party?",
    "How do I make a delicious and healthy frittata?",
    "What's the best way to clean my terrazzo floors?",
    "How do I create a cozy and inviting balcony?",
    "What are some tips for improving my sales skills?",
    "How do I choose the right gerbil habitat for my furry friend?",
    "What's a good way to organize my recording studio and equipment?",
    "How do I create a beautiful and community garden?",
    "What are some tips for a successful tequila tasting party?",
    "How do I make a delicious and healthy quiche?",
    "What's the best way to clean my marble floors?",
    "How do I create a functional and stylish media room?",
    "What are some tips for improving my customer service skills?",
    "How do I choose the right mouse habitat for my furry friend?",
    "What's a good way to organize my dance studio and equipment?",
    "How do I create a beautiful and guerrilla garden?",
    "What are some tips for a successful vodka tasting party?",
    "How do I make a delicious and healthy crepe?",
    "What's the best way to clean my granite floors?",
    "How do I create a cozy and inviting deck?",
    "What are some tips for improving my management skills?",
    "How do I choose the right rat habitat for my furry friend?",
    "What's a good way to organize my yoga studio and equipment?",
    "How do I create a beautiful and market garden?",
    "What are some tips for a successful rum tasting party?",
    "How do I make a delicious and healthy pancake?",
    "What's the best way to clean my slate floors?",
    "How do I create a functional and stylish game room?",
    "What are some tips for improving my marketing skills?",
    "How do I choose the right degu habitat for my furry friend?",
    "What's a good way to organize my pilates studio and equipment?",
    "How do I create a beautiful and moon garden?",
    "What are some tips for a successful gin tasting party?",
    "How do I make a delicious and healthy waffle?",
    "What's the best way to clean my travertine floors?",
    "How do I create a cozy and inviting porch?",
    "What are some tips for improving my project management skills?",
    "How do I choose the right chinchilla habitat for my furry friend?",
    "What's a good way to organize my personal training studio and equipment?",
    "How do I create a beautiful and native plant garden?",
    "What are some tips for a successful brandy tasting party?",
    "How do I make a delicious and healthy french toast?",
    "What's the best way to clean my soapstone floors?",
    "How do I create a functional and stylish home gym?",
    "What are some tips for improving my financial literacy?",
    "How do I choose the right sugar glider habitat for my furry friend?",
    "What's a good way to organize my massage therapy studio and equipment?",
    "How do I create a beautiful and organic garden?",
    "What are some tips for a successful liqueur tasting party?",
    "How do I make a delicious and healthy muffin?",
    "What's the best way to clean my limestone floors?",
    "How do I create a cozy and inviting sun porch?",
    "What are some tips for improving my digital literacy?",
    "How do I choose the right hedgehog habitat for my furry friend?",
    "What's a good way to organize my acupuncture clinic and supplies?",
    "How do I create a beautiful and perennial garden?",
    "What are some tips for a successful cocktail party?",
    "How do I make a delicious and healthy scone?",
    "What's the best way to clean my quartzite floors?",
    "How do I create a functional and stylish mudroom?",
    "What are some tips for improving my emotional intelligence?",
    "How do I choose the right ferret habitat for my furry friend?",
    "What's a good way to organize my chiropractic clinic and supplies?",
    "How do I create a beautiful and pollinator garden?",
    "What are some tips for a successful barbecue?",
    "How do I make a delicious and healthy biscuit?",
    "What's the best way to clean my onyx floors?",
    "How do I create a cozy and inviting four-season room?",
    "What are some tips for improving my physical fitness?",
    "How do I choose the right rabbit habitat for my furry friend?",
    "What's a good way to organize my veterinary clinic and supplies?",
    "How do I create a beautiful and sensory garden?",
    "What are some tips for a successful picnic?",
    "How do I make a delicious and healthy croissant?",
    "What's the best way to clean my sandstone floors?",
    "How do I create a functional and stylish laundry room?",
    "What are some tips for improving my mental health?",
    "How do I choose the right bird habitat for my feathered friend?",
    "What's a good way to organize my optometry clinic and supplies?",
    "How do I create a beautiful and therapeutic garden?",
    "What are some tips for a successful camping trip?",
    "How do I make a delicious and healthy doughnut?",
    "What's the best way to clean my slate floors?",
    "How do I create a cozy and inviting finished basement?",
    "What are some tips for improving my spiritual well-being?",
    "How do I choose the right fish habitat for my aquatic friend?",
    "What's a good way to organize my physical therapy clinic and supplies?",
    "How do I create a beautiful and water-wise garden?",
    "What are some tips for a successful road trip?",
    "How do I make a delicious and healthy bagel?",
    "What's the best way to clean my travertine floors?",
    "How do I create a functional and stylish attic conversion?",
    "What are some tips for improving my social connections?",
    "How do I choose the right reptile habitat for my scaly friend?",
    "What's a good way to organize my occupational therapy clinic and supplies?",
    "How do I create a beautiful and woodland garden?",
    "What are some tips for a successful hiking trip?",
    "How do I make a delicious and healthy pretzel?",
    "What's the best way to clean my soapstone floors?",
    "How do I create a cozy and inviting garage conversion?",
    "What are some tips for improving my personal growth?",
    "How do I choose the right invertebrate habitat for my invertebrate friend?",
    "What's a good way to organize my speech therapy clinic and supplies?",
    "How do I create a beautiful and Zen garden?"
];
